### ISSUE TITLE
It runs only the first batch and won't resolve the promise

### ISSUE THREAD

**Issue by willemdewit** [dfabulich/concurrency-limit-runner#1]
The example provided in the readme only runs the first batch of the concurrent promises. The output is:
```
start 0
start 1
start 2
end 1
end 2
end 0
```
The expected result should also start the next promises and count to 20. 
Tested in Chrome and Safari.

**Comment by dfabulich** [comment]
I don't reproduce this. Here's an HTML file that I used to try to reproduce it:

```
<!DOCTYPE html>
<html>
<head>
<script type="module">
import { runTasks } from 'https://www.unpkg.com/concurrency-limit-runner@1.0.0/index.mjs';

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

const tasks = [];
for (let i = 0; i < 20; i++) {
    tasks.push(async () => {
        console.log(`start ${i}`);
        await sleep(Math.random() * 1000);
        console.log(`end ${i}`);
        return i;
    });
}

for await (const value of runTasks(3, tasks.values())) {
    console.log(`output ${value}`);
}

console.log('done');
</script>
</head>
<body>
</body>
</html>
```

When I open it and then view the console, I see exactly what I'd expect, 20 tasks run to completion. I tested this in Chrome 124 and in Safari 17.5.

```
start 0
start 1
start 2
end 1
start 3
output 1
end 0
start 4
output 0
end 2
start 5
output 2
end 3
start 6
output 3
end 4
start 7
output 4
end 6
start 8
output 6
end 8
start 9
output 8
end 5
start 10
output 5
end 7
start 11
output 7
end 9
start 12
output 9
end 10
start 13
output 10
end 11
start 14
output 11
end 13
start 15
output 13
end 12
start 16
output 12
end 16
start 17
output 16
end 15
start 18
output 15
end 18
start 19
output 18
end 17
output 17
end 14
output 14
end 19
output 19
done
```

**Comment by willemdewit** [comment]
Thank you for the quick reply! I tested your code as well, it seems to work correctly outside of my app environment. 
Then I suspect that the babel compiler screws things up. It compiles to this:

```
 var sleep, tasks, _loop, i, _iteratorAbruptCompletion, _didIteratorError, _iteratorError, _iterator, _step, value;
        return _regeneratorRuntime().wrap(function _callee6$(_context7) {
          while (1) switch (_context7.prev = _context7.next) {
            case 0:
              sleep = function _sleep(ms) {
                return new Promise(function (r) {
                  return setTimeout(r, ms);
                });
              };
              tasks = [];
              _loop = /*#__PURE__*/_regeneratorRuntime().mark(function _loop(i) {
                return _regeneratorRuntime().wrap(function _loop$(_context6) {
                  while (1) switch (_context6.prev = _context6.next) {
                    case 0:
                      tasks.push( /*#__PURE__*/_asyncToGenerator( /*#__PURE__*/_regeneratorRuntime().mark(function _callee5() {
                        return _regeneratorRuntime().wrap(function _callee5$(_context5) {
                          while (1) switch (_context5.prev = _context5.next) {
                            case 0:
                              console.log("start ".concat(i));
                              _context5.next = 3;
                              return sleep(Math.random() * 1000);
                            case 3:
                              console.log("end ".concat(i));
                              return _context5.abrupt("return", i);
                            case 5:
                            case "end":
                              return _context5.stop();
                          }
                        }, _callee5);
                      })));
                    case 1:
                    case "end":
                      return _context6.stop();
                  }
                }, _loop);
              });
              i = 0;
            case 4:
              if (!(i < 20)) {
                _context7.next = 9;
                break;
              }
              return _context7.delegateYield(_loop(i), "t0", 6);
            case 6:
              i++;
              _context7.next = 4;
              break;
            case 9:
              _iteratorAbruptCompletion = false;
              _didIteratorError = false;
              _context7.prev = 11;
              _iterator = _asyncIterator(runTasks(3, tasks.values()));
            case 13:
              _context7.next = 15;
              return _iterator.next();
            case 15:
              if (!(_iteratorAbruptCompletion = !(_step = _context7.sent).done)) {
                _context7.next = 21;
                break;
              }
              value = _step.value;
              console.log("output ".concat(value));
            case 18:
              _iteratorAbruptCompletion = false;
              _context7.next = 13;
              break;
            case 21:
              _context7.next = 27;
              break;
            case 23:
              _context7.prev = 23;
              _context7.t1 = _context7["catch"](11);
              _didIteratorError = true;
              _iteratorError = _context7.t1;
            case 27:
              _context7.prev = 27;
              _context7.prev = 28;
              if (!(_iteratorAbruptCompletion && _iterator.return != null)) {
                _context7.next = 32;
                break;
              }
              _context7.next = 32;
              return _iterator.return();
            case 32:
              _context7.prev = 32;
              if (!_didIteratorError) {
                _context7.next = 35;
                break;
              }
              throw _iteratorError;
            case 35:
              return _context7.finish(32);
            case 36:
              return _context7.finish(27);
            case 37:
              console.log('done');
            case 38:
            case "end":
              return _context7.stop();
          }
        }, _callee6, null, [[11, 23, 27, 37], [28,, 32, 36]]);
```

**Comment by dfabulich** [comment]
I'm not sure what's up with the Babel transformation. It looks like this is just a snippet out of a larger transformation; I can't see your Babel configuration or repro the Babel issue.

I did try copying and pasting `concurrency-limit-runner` minus the `export` keyword into the [Babel playground](https://babeljs.io/repl#?browsers=ie%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=PTAEAEBcGcFoGMAWBTeBrAUB4AqHHQcJJkBbABwBsBDE0AFQKPHOoCdrTQBvAOwFdSAI2RsAvqFLUAHgGEA9r3j82bZEoCeoJhFYcu3AJIkOQysmOja8tgB4AFAEpQAXgB8oAApt5pAJbQyLb0bm4SkNTQaJYckDbahBBqkCq80KAAgtAaSgDi6lZxdiFMwBiROfCgAGb8SpB-ikRsdfSRaND2UnKKyqrq8BoANKARUTHWbM7cBKBzFUo1dfANTaDwarTIAOo2aKITRU48s3NnoCCgAKLUSJnZeQWx8ZCItKOIAUv1jbxEG8gtukvtRQAB3PaiIanc4XMDkeSUSh-XgAcxqL3a6WqPi4r2QoGgbzUABNRu1DjYAHSgADKxJR6PxMPOlzG0RMk1A6mgKmQ6Ve70BdwhbH2bFAqOQMFAdT8AEd-AT2dAqSyztV4vZ4IpoJByVFQPJqgaOYUbM4NH5kJQydQwdQ_Pr2U4ANwwsRYc46tL6hbwSlsdIuUC8ZBgzKqagaLoyBRKFRqTSOd3nTUS-zmfV-VygAAMrtAOdskjjvUTAw0hb8AGoa9N1fMHgHOUVoABtPwAXVzAK2uzFB1bNjdHphVptJOat2QWUqgc6_oXKYwnuweB0UDIVC2DE3ek4PDnSkDwTc7a7EiXw6Dm-SqXSx_g-TDz2KblK5Wb3xWv2n8FnZsF3sa9zSDBtWTwXR2EPbgn1PEIJCdMDCDKc5_R_VZeFDZBpEgAAlfl-EoSBtidRBjGgQN7GQt8INhOZ7zYbDuFANReRIgAuUB7UdbMbypMM8KcEZaMmbixKKUAxFTM410g5hIA0cgCW4ABZahyFseCbzPEZvF8AIgm4djiMgbjA0IjjID0osb24nSwLPMRQgkHA0LOH09VAchcSM4McIjDTyFHNMtS8_iUONHigJvaB6IY3zDMCVVAkgGibxGISCKIkiyNeSjqMki0V3OT1zjBT5zFAewkv8FKqWgPwAC9kAS2EIp4NjcsgUSb2k3NeKdLw_MCKkOAA2rRv5KkADdqEoJVOkcUqGKLE17FMkiqRJRQ2pONbYTq_ydptaVkAysDVoYiQbUCA7DrOY6GrSy63yy3Ccus_KKJgIqbxW2THtACdbW66y5oWpUgdhcq5NXIA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env&prettier=false&targets=&version=7.24.5&externalPlugins=&assumptions=%7B%7D) and copied and pasted that into a test HTML file, attached, and it worked just fine.
[babel-test.zip](https://github.com/dfabulich/concurrency-limit-runner/files/15338491/babel-test.zip)

FWIW, it looks like the way you've configured Babel, it's trying to transpile `function*` down to non-`function*` code. That should still work, and, if it doesn't, that's either a bug in Babel (unlikely) or a bug in your code.

But, hear me out, I really think you should change your Babel configuration so it stops transpiling this code.

`function*` has been supported since ES6. https://caniuse.com/es6-generators It's been supported on all browsers since 2018. Caniuse reports 97.45% global usage, which is actually an understatement https://github.com/Fyrd/caniuse/issues/6813 … if you switch it to "all tracked," you'll find that 99.12% of users can use `function*`.

Your Babel configuration is transpiling down past ES6 to ES5 (IE11 support), and generating a bunch of illegible boilerplate, which hurts performance for all of your users, to benefit less than 1% of your users.
